---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /{tableName}:
    get:
      parameters:
        - name: tableName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      parameters:
        - name: tableName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /{tableName}/filter/{logic}:
    post:
      parameters:
        - name: logic
          in: path
          required: true
          schema:
            type: string
        - name: tableName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /{tableName}/{id}:
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int32
            type: integer
        - name: tableName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /{tableName}/{id}/{parameterToChange}:
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int32
            type: integer
        - name: parameterToChange
          in: path
          required: true
          schema:
            type: string
        - name: tableName
          in: path
          required: true
          schema:
            type: string
        - name: value
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
